### ISSUE TITLE
Feature request - put UI on a separate thread so it remains responsive

### ISSUE THREAD

**Issue by RichardJECooke** [thargor6/JWildfire#278]
I've noticed in lots of places in JWildfire the whole app freezes - for instance when using 'mutagen' to generate new fractals, or clicking the quick 'render' button in the main app.

It would be great if intead
1) feedback is shown to the user by means of a spinner when the app is processing so the user knows it hasn't crashed and force quits (like any webpage)
2) the app doesn't freeze at all - but rather rendering is done on a separate thread so we can still close windows and use the UI while it's working - and cancel operations that are taking too long

**Comment by thargor6** [comment]
We are already working on this for the last years, so you will also find lots of places where it was already changed. But, still a valid point.

Cheers!
