### ISSUE TITLE
Feature request - Create manual/wiki that is up to date

### ISSUE THREAD

**Issue by RichardJECooke** [thargor6/JWildfire#279]
There are so many buttons that aren't immediately apparent - like what does 'add final' transform do that's different to a normal transform?  What is 'post-transform mode toggle? Why does the camera have 'centrex' and 'camposx' when they do the same thing?

You can't learn this stuff browsing tutorials as a newbie. The app needs either lengthy tooltips on each button, or a long reference page on a wiki that lists what everything that it does.

**Comment by snicker02** [comment]
Just my 2 cents but it may be more productive if you post feature requests on the official forum here http://jwildfire.org/forum/viewforum.php?f=14

**Comment by RichardJECooke** [comment]
Thanks! Didn't know about this. I'm used to projects using the repo. I'll use the forum from now
