### ISSUE TITLE
Support HiDPI scale on Linux

### ISSUE THREAD

**Issue by kikohs** [thargor6/JWildfire#282]
I can't run JWildFire 5 (or 4.1) properly on a 4k screen on ubuntu at 200% UI scale.
The UI scale parameter before launching the app doesn't do anything.
I read that Java 9 solved the issue but would need recompilation.

`-Dsun.java2d.uiScale=2.0`  has no effect on my system.

**Comment by Chess13234** [comment]
Same here. On a 1920x1080 screen, the font is so tiny its unusable. 
![Image of Yaktocat](https://i.imgur.com/XXiY3O9.png)

**Comment by thargor6** [comment]
I just checked it on Ubuntu, and it worked fine. But, I use Java 11, maybe it worked not well in Java 9.
