### ISSUE TITLE
bug - delete transformation function is broken

### ISSUE THREAD

**Issue by Euphorbium** [thargor6/JWildfire#311]
After deleting a transformation, the image disappears. I can add the same transformation after that, but nothing is rendered, the image does not reappear. Only happens when the last transformation is deleted.
I am on a mac, version 5.5

**Comment by thargor6** [comment]
You should use more restrained language like "The entire ... function is broken", as it more seems that you do not fully understand what you are doing. Of course, the function is not entirely broken, as it is a mature piece of software with now version 5.5. You can trust us that  basic functions are not entirely broken.
Your case can not be duplicated. Of course, the "image" does appear again when you add the same transforms.

**Comment by Euphorbium** [comment]
Sorry for my language, but did you try removing the last transformation? I can provide a video showing that the image does not reappear after adding the same transformation.

**Comment by Euphorbium** [comment]
Oh, I narrowed it down a little bit more, the last transformation needs to be linked (added by pressing L button), for this bug to manifest.

**Comment by thargor6** [comment]
You are struggling with some convenience function: Linking transforms modifies relative weights. Adding transforms takes into account relative weights. So, after deleting and adding the linked transform, it is the same transform, but with zero relative weights. So it has no effect. You must reset the relative weights. Or just use undo to "undelete" the transform.

**Comment by Euphorbium** [comment]
Thanks. Why does the view disappear after deleting the linked transform? How are the relative weights reset?

**Comment by thargor6** [comment]
Sorry, I have no time to discuss this here. Please use the forum to ask questions regarding concepts etc. Cheers!
