### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by lahiruc** [thargor6/JWildfire#336]
When build.gradle file executes below error occurs.

![image](https://user-images.githubusercontent.com/43800563/87801343-3b4b4300-c86d-11ea-96bf-241156c6d704.png)

What could be the reason for this ?

It worked to some extent after changing the Gradle Version (from '2.4' to the latest)

Better if you can give a solution / suggestion for this. 

@thargor6  **Can you provide a suggestion ?**
Thank you.

**Comment by thargor6** [comment]
the gradle-build is currently unsupported, we still are using the ant-build. 
to make it work with gradle would be nice, but currently has a low priority on my large TODO-list.
