### ISSUE TITLE
Index 0 Out of Bounds for Length 0 in Batch-Renderer

### ISSUE THREAD

**Issue by Nuyube** [thargor6/JWildfire#376]
I was rerendering some old flames I had with the new OptiX denoiser, and I ran into this error:
![image](https://user-images.githubusercontent.com/81436002/115152279-81247a00-a03e-11eb-8ab5-0988b4522835.png)

Attached are four flame files that all share the same error. I can update with more if more fail to render.
[Flames.zip](https://github.com/thargor6/JWildfire/files/6331676/Flames.zip)

Currently running JWildFire 6.50 (I downloaded it yesterday from the website.)

**Comment by thargor6** [comment]
Those files seem to be just garbage (use text-viewer to review, normally a
*.flame file is some kind of an xml-file), so the software can not parse
them. I agree that the error message has room for improvement.

Cheers!

Am So., 18. Apr. 2021 um 18:08 Uhr schrieb Nuyube ***@***.***

**Comment by Nuyube** [comment]
Oh, I guess somewhere along the way, these files got copied incorrectly. Sorry about that!
