### ISSUE TITLE
Building on macOS Catalina 10.15

### ISSUE THREAD

**Issue by two-taps** [thargor6/JWildfire#399]
Hi.

I do have java installed.

I downloaded the code, went in the `build/launcher` file for macOS and I get the following error:

`Error: Unable to access jarfile ./j-wildfire-launcher.jar`

So I opened the .command file to see where the jar file was located so I went into the `lib` folder and ran the command just like in the `.command` file:

`JWildfire/lib -$ java -Dapple.eawt.quitStrategy=CLOSE_ALL_WINDOWS -jar j-wildfire-lib.jar`

and I get this error:

`Error: Invalid or corrupt jarfile j-wildfire-lib.jar`

I tried re downloading the code but I keep getting the same error. What should I do?

Thanks in advance

**Comment by thargor6** [comment]
you should build and run j-wildfire.jar, not j-wildfire-lib.jar, which is a
lib, which can not run

Cheers!

Am Do., 16. Sept. 2021 um 02:15 Uhr schrieb Gustavo León <
***@***.***>:

**Comment by two-taps** [comment]
oh I see.

Where is that jar file located? I made a `find j-wildfire.jar` and couldn't find it.

I used the GitHub go to file as well.... it's not existent. Where is it if you can help me?

I searched for j-wildfire.jar and j-wildfire-launcher.jar (as it says on the .command file) but nothing found.

**Comment by thargor6** [comment]
j-wildfire.jar is the result of the build process. I thought you were
saying that you are building it?

Am Do., 16. Sept. 2021 um 05:43 Uhr schrieb Gustavo León <
***@***.***>:

**Comment by two-taps** [comment]
Oh that makes sense.

I can't find out how to build it. I read all the readme files but can't find out how. I thought I could build it running the `start_mac.command` file

**Comment by thargor6** [comment]
I'm confused now ;-) When you do not know how to build, why you do not just
download the pre-built version?

Am Do., 16. Sept. 2021 um 19:37 Uhr schrieb Gustavo Leon <
***@***.***>:

**Comment by two-taps** [comment]
Because it's paid and I don't have money right now to buy the paid appstore version): I thought I could just compile the .java files and it would work...but I guess I need to do more than that

**Comment by thargor6** [comment]
just download the free version

Am Do., 16. Sept. 2021 um 21:51 Uhr schrieb Gustavo Leon <
***@***.***>:

**Comment by two-taps** [comment]
Oh were is it...? I tried to find it for MacOS but it forwards me to the appStore only

**Comment by thargor6** [comment]
http://blog.overwhale.com/

Am Do., 16. Sept. 2021 um 21:54 Uhr schrieb Gustavo Leon <
***@***.***>:
