### ISSUE TITLE
Running from Terminal

### ISSUE THREAD

**Issue by edwint88** [thargor6/JWildfire#402]
I'm on MacOS and when I try to run the headless renderer I don't get any output files (following this: https://github.com/thargor6/JWildfire/wiki/CLI-tools) 

`22:07:04,297 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:07:04,297 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:07:04,297 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/zartu/Applications/j-wildfire-7.00/lib/j-wildfire.jar!/logback.xml]
22:07:04,310 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@25084a1e - URL [jar:file:/Users/zartu/Applications/j-wildfire-7.00/lib/j-wildfire.jar!/logback.xml] is not of type file
22:07:04,362 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
22:07:04,363 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
22:07:04,369 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
22:07:04,376 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
22:07:04,402 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [/Users/zartu/JWildfire.log]
22:07:04,403 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:07:04,404 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
22:07:04,404 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
22:07:04,406 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.jwildfire.swing.MessageLogFrameAppender]
22:07:04,406 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MESSAGE_LOG]
22:07:04,407 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:18 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
22:07:04,407 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@19:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
22:07:04,407 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
22:07:04,408 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
22:07:04,408 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
22:07:04,408 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [MESSAGE_LOG] to Logger[ROOT]
22:07:04,408 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:07:04,409 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@156b88f5 - Registering current configuration as safe fallback point

Done
128251 ms
`

I'm running the last version 7.00

Another topic: 
Is there a way to call the scripts from CLI?

**Comment by thargor6** [comment]
the inclusion of svgSalamander.jar instead of svgSalamander.jar broke the build for me. It adds some crazy files to the META-INF, so java will not recognize the main class.
When I revert to svgSalamander-tiny.jar, it works again.

**Comment by edwint88** [comment]
I don't know how this works for you, because in lib that doesn't exists (maybe you have to try from a fresh environment, not to have old dependencies or files in it). About the META-INF I can agree with you, there is something strange happening and not working too good. Maybe as a solution add the tiny.jar back to lib and use that.

**Comment by thargor6** [comment]
I have today released the new CLI: http://blog.overwhale.com/?p=5766, which should work out-of-the-box, also on Mac

Cheers!
