### ISSUE TITLE
GPU Rendering causes black screen

### ISSUE THREAD

**Issue by madomdy** [thargor6/JWildfire#406]
So I run the JWildfire software on a fresh GPU backed instance (uses NVIDIA P6000) on Windows, CUDA is available. Installation was done through Steam. Version is 7.30.

While rendering works just fine on CPU, switch to GPU Rendering leads to either black image, or StackTrace error. What are the possible updates to preferences I can do to make it work?

<img width="689" alt="Screenshot 2022-01-15 at 18 50 31" src="https://user-images.githubusercontent.com/5181983/149658670-678ed4fa-61d8-4f43-a76b-594cea317bc1.png">
<img width="552" alt="Screenshot 2022-01-16 at 13 46 11" src="https://user-images.githubusercontent.com/5181983/149658675-22638d08-d0d9-45ad-a36d-a94eb2ea51d5.png">
<img width="1786" alt="Screenshot 2022-01-16 at 13 50 09" src="https://user-images.githubusercontent.com/5181983/149658732-5cf34082-b653-48cf-96c4-1a1af8d70757.png">

**Comment by thargor6** [comment]
Changes to Prefs will not fix this, as in the most cases such problems are caused by drivers issues.
Sounds like you are using a virtual machine which I think was never tested before.
I have planned to include some diagnostic script/tool in future releases.

**Comment by madomdy** [comment]
Got it, thank you! It actually has usual up to date NVIDIA drivers installed. Maybe you have some recommendations on drivers/cuda version required, so maybe I have to downgrade?

Should I try to get hardware myself, you suppose that will make a difference?

**Comment by thargor6** [comment]
Newest drivers should be fine. I have no experience with P6000 yet, but more regular ones like 1xxx-2xxxx should work fine. 
Before obtaining  a specific card, I would recommend to test it if possible, the devil is always in the detail, especially for GPU computing. For testing, you will not need the Steam version.
