### ISSUE TITLE
Context menu for adding new subflame is missing

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#411]
Since 2-3 versions the subflame editor doesn't have the context menu for pasting flames anymore. I don't remember what else was in the context menu.

Add a variation and make it subflame.
<img width="1188" alt="Screenshot 2023-02-20 at 05 04 01" src="https://user-images.githubusercontent.com/1361928/220007119-91cddb30-be9e-49db-beab-79702aa26d17.png">

Click on the gear icon to show the flame. Some versions ago there was a context menu. But now I can only use "Open file" to add a flame.
<img width="800" alt="Screenshot 2023-02-20 at 05 04 17" src="https://user-images.githubusercontent.com/1361928/220007212-1d641f25-9d1f-4bdf-88f7-099c005c85b0.png">

**Comment by thargor6** [comment]
This is probably becauise it is now a different UI-component which has no contextg-menu by default.

I have now added a context-menu to the resources-dialog for editing text (copy, cut, paste)
