### ISSUE TITLE
Security scoped bodgemarks not working

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#412]
Every time I start JWildfire I have to select the path for the scripts.

Yesterday:
<img width="1179" alt="Screenshot 2023-02-19 at 17 51 04" src="https://user-images.githubusercontent.com/1361928/220007609-ad5ac1dc-1b01-49cd-9077-720b3f3a5554.png">

Today:
<img width="1319" alt="Screenshot 2023-02-20 at 05 08 12" src="https://user-images.githubusercontent.com/1361928/220007631-d2b47efd-7622-429f-aaae-3b5bbe290c2f.png">

**Comment by beatrixwillius** [comment]
For the custom variations the SSBs are working:
<img width="800" alt="Screenshot 2023-02-20 at 05 21 21" src="https://user-images.githubusercontent.com/1361928/220056347-a6d2dc44-47cf-4f44-bd8b-0ec79ccf9ce0.png">

Weird!

**Comment by thargor6** [comment]
There seems to be some extra space character in the the path to your scripts folder (".../jwildfire/ scripts").
Maybe this causes the problem? (I just tested it on my machine (Ventura): it also works with the scripts folder)

**Comment by beatrixwillius** [comment]
Any path with a space causes the message "please select the folder" to show up when starting JWildfire.

**Comment by thargor6** [comment]
So when you remove the space it works?

**Comment by beatrixwillius** [comment]
Yes, it works without space. For testing I tried "scripts test" to see if the space at the beginning is a problem. But "scripts test" also failed.

**Comment by thargor6** [comment]
I have added a check for path-settings which contain space-characters and display a warning in this case

**Comment by beatrixwillius** [comment]
Not really a good idea. The main user on my iMac has a space "beatrixwillius 1". Which means that all paths have a space:
<img width="1015" alt="Screen Shot 2023-02-25 at 14 32 24" src="https://user-images.githubusercontent.com/1361928/221359808-0191498f-077c-48f3-a939-2301dc6aae58.png">

**Comment by thargor6** [comment]
I think it is. I have spent so much time of my life with exactly this problem (spaces in paths, of course not only in JWildfire, but in so many other systems), that it is enough now. Sorry, when this causes inconveniences for you.

**Comment by beatrixwillius** [comment]
Weird. Except my user with the space I never had any problem with spaces in paths.

**Comment by thargor6** [comment]
added an option "skipPathCheckAtStartup" in the Preferences to skip the check for valid paths at program startup
