### ISSUE TITLE
Don't make me change 4 dropdown menus for the mutations

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#413]
I have set my mutations so that user1 makes structural changes, user2 changes parameters and user3 changes the color:
<img width="1220" alt="Screenshot 2023-02-20 at 05 13 18" src="https://user-images.githubusercontent.com/1361928/220008193-65bea589-b065-48d1-8c97-14b2327ee72d.png">

Every time I want to switch I need to change 4 dropdown menus:

<img width="1000" alt="Screenshot 2023-02-20 at 05 12 54" src="https://user-images.githubusercontent.com/1361928/220008320-296da7d9-2c17-46d4-b12f-5d51e5b68fae.png">

Please simplify the interface.

**Comment by thargor6** [comment]
The most simple way would be to save the last selection. Would this solve the problem?

**Comment by beatrixwillius** [comment]
No, I don't care about saving the last selection. I haven't a clue how other users use this part of the interface. I start with making large mutations, then I fine tune the parameters and then I make a nice gradient. So switching the values is the annoyance for me.

**Comment by thargor6** [comment]
Ah, so you are always using the same value for each of the 4 listboxes? (this was not obvious because it is not intended this way. But interesting). A solution would be to have just one listbox (as alternative interface)

**Comment by beatrixwillius** [comment]
Yup. That's my workflow. But I don't know how others use the mutations.

**Comment by thargor6** [comment]
After thinking about this for a while I came to the conclusion that the current "intended" way of usage does not make sense, i. e. gives too much control where it is not needed. Will change it, so that there will remain only one listbox.

**Comment by thargor6** [comment]
changed. Indeed works mor fluid now. Thanks for the suggestion!
