### ISSUE TITLE
Preview for batch file only visible with the second file

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#414]
Have some random flames:

<img width="1188" alt="Screenshot 2023-02-20 at 05 48 00" src="https://user-images.githubusercontent.com/1361928/220054446-ed7bbc77-88a1-438f-821f-a0274e1158e9.png">

Add the file to batch render. But there is no preview:
<img width="1083" alt="Screenshot 2023-02-20 at 05 48 24" src="https://user-images.githubusercontent.com/1361928/220054675-37f1982e-ab68-4060-9e50-b89a2de352fe.png">

Add a second flame to the batch render. Now the preview for both flames shows up:

<img width="1083" alt="Screenshot 2023-02-20 at 05 48 46" src="https://user-images.githubusercontent.com/1361928/220054759-3cab1145-ba9c-492c-874f-34005b236378.png">

**Comment by thargor6** [comment]
fixed
