### ISSUE TITLE
Scrollbars in listbox have artefacts when scrolling

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#415]
Scroll down a listbox and get some nice artefacts in the scrollbar:

<img width="1188" alt="Screenshot 2023-02-20 at 05 49 09" src="https://user-images.githubusercontent.com/1361928/220055696-a5a0a96d-f442-41c2-9cfe-e9197451d503.png">
<img width="800" alt="Screenshot 2023-02-20 at 05 49 31" src="https://user-images.githubusercontent.com/1361928/220055715-ce60ba84-bbf4-48bf-bfd3-1e7f95c515e0.png">

The slower I scroll the more artefacts:
<img width="800" alt="Screenshot 2023-02-20 at 05 49 54" src="https://user-images.githubusercontent.com/1361928/220055846-db363767-c952-4b80-83dd-7146b046ecf4.png">

When scrolling up the artefacts are hidden. 

I also get the artefacts after switching themes:
<img width="1178" alt="Screenshot 2023-02-20 at 09 41 11" src="https://user-images.githubusercontent.com/1361928/220055984-44225251-ba00-4535-a42b-f065fabbc6d2.png">

Ventura 13.2 on M1

**Comment by thargor6** [comment]
I think I can not do much here (is inside the JTattoo-libary).
My advice would be to use the Default Nimbus-Theme which is the only one which is "officially supported".

**Comment by thargor6** [comment]
Can see no way to fix that (other then rewriting the app in Swift ;-))
When it gets too annyoing try to use the Nimbus-Theme.
->Closed
