### ISSUE TITLE
Changing path is wonky

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#416]
Lets say I want to change tinaCustomVariationsPath:

<img width="800" alt="Screenshot 2023-02-20 at 05 21 21" src="https://user-images.githubusercontent.com/1361928/220056732-bc193131-f27c-47c9-86d1-3385a4116ac1.png">

Double clicking on the path makes the path hide:
<img width="800" alt="Screenshot 2023-02-20 at 05 21 31" src="https://user-images.githubusercontent.com/1361928/220056820-365ba87b-fd1d-4cf3-9c2e-1b51fc9e5d8b.png">

After some frantic clicking I somehow get the button with the 3 dots to show up again:
<img width="800" alt="Screenshot 2023-02-20 at 05 21 37" src="https://user-images.githubusercontent.com/1361928/220056916-4842580e-24f7-49e4-80ab-1122c70635e0.png">

Please change the path so that the button with the 3 dots is always visible.

**Comment by thargor6** [comment]
made the properties-editor in the Preferences-window more accessible, increased the size of the button for selecting folders, must check this later on Mac. unfortunately the component used here has some Mac-specific behaviour.
