### ISSUE TITLE
variation PRose3DFunc: Method uses the same code for two branches

### ISSUE THREAD

**Issue by smack42** [thargor6/JWildfire#42]
Detected by FindBugs in class  JWildfire/src/org/jwildfire/create/tina/variation/PRose3DFunc.
The fix would be trivial, just remove the redundant code.

However, I think this can be a real error and that the `if/else` paths should have contained different code. Please verify.

```java
    else // this is the option when optDir > 0.0
    {
      if (posNeg < 0)
      {
        pVarTP.x += pAmount * 0.5 * (length * cos(numPetals * th + constant)) * cth;
        pVarTP.y += pAmount * 0.5 * (length * cos(numPetals * th + constant)) * sth;
        pVarTP.z += pAmount * 0.5 * ((scaleZ1 * waggle + sqr(rad * 0.5) * sin(wig) * wigScale) + (this.dist));

      }
      else
      {
        pVarTP.x += pAmount * 0.5 * (length * cos(numPetals * th + constant)) * cth;
        pVarTP.y += pAmount * 0.5 * (length * cos(numPetals * th + constant)) * sth;
        pVarTP.z += pAmount * 0.5 * ((scaleZ1 * waggle + sqr(rad * 0.5) * sin(wig) * wigScale) + (this.dist));
      }
    }
  }
```

**Comment by thargor6** [comment]
Interesting, but I did not create this variation, so I'm not sure what was intended. I think, it is better to remove it

**Comment by smack42** [comment]
Agreed, lets remove it. The original C-code contains the same code duplication.
http://aporev.deviantart.com/gallery/#/d2blmhg
