### ISSUE TITLE
Don't do binary sorting

### ISSUE THREAD

**Issue by beatrixwillius** [thargor6/JWildfire#420]
All sorting in JWildfire is done with binary sorting:

A
Z
a
z
<img width="293" alt="Screenshot 2023-03-04 at 14 23 42" src="https://user-images.githubusercontent.com/1361928/222904435-8c08a3c6-ee82-4955-a801-19aa721bae8d.png">

Please use normal lexical sorting and sort the lowercase with the uppercase.

**Comment by thargor6** [comment]
changed
