### ISSUE TITLE
Certain values get ignored when rendering a fractal in GPU mode

### ISSUE THREAD

**Issue by volantmusic** [thargor6/JWildfire#422]
![image](https://user-images.githubusercontent.com/109357673/224853897-1f1ac2ed-4bb2-4581-9412-d32f417c0fbb.png)
As you can see on the top right, the camera is supposed to be ON the fractal, but in the render it is not. I believe the CenterX and CenterY values get ignored for some reason. 
[hyperin6.zip](https://github.com/thargor6/JWildfire/files/10962683/hyperin6.zip)

**Comment by volantmusic** [comment]
Version used was 8.00.

**Comment by thargor6** [comment]
not sure if this is an option for you: it is very likely that you can circumvent this problem by disabling GPU render, until there is a fix. There sees to be an incompatiblitys in treatment of camera settings between GPU and CPU render, but it is not obvious.

**Comment by volantmusic** [comment]
I can do that, but it means this is going to render something like 10k seconds per flame. I can make that on time for sure, but it would be good if this was fixed since GPU rendering is so much more efficient for projects.

**Comment by thargor6** [comment]
Sure, I hope I can fix that soon.

**Comment by thargor6** [comment]
fixed calculation of camera angle of the CUDA-renderer (was off when roll was not zero)
