### ISSUE TITLE
Adding PNG Sequence Export to Batch Renderer (as an option)

### ISSUE THREAD

**Issue by volantmusic** [thargor6/JWildfire#423]
Not sure if this is caused by JWildfire or my computer's software, but is there a way to export .png sequences out of the Batch Renderer window to avoid these sorts of encoding glitches? If not, could be a feature (since it already exports .png sequences first)
![image](https://user-images.githubusercontent.com/109357673/225152954-a606430d-94c1-4247-bdee-54892cc8cafb.png)

**Comment by thargor6** [comment]
Until this is implemented in another way: you can achieve this by setting the property **tinaKeepTempMp4Frames** in the Preferences. So you will have both, the *.mp4 file and the image-sequence

**Comment by volantmusic** [comment]
Thank you! Very big help
