### ISSUE TITLE
JWF 8, Steam Version

### ISSUE THREAD

**Issue by mcculleymike** [thargor6/JWildfire#433]
I used Steam to setup my JWildfire for the first time. It takes quite a time to load, but I think it is working now. I have noticed that all my settings files are incorrect. For Flames, Image Paths, etc. Where does Steam put the JWildfire program files? I cannot find the new 8.0 version folder, that it was installed in. I need that to set up all my default directories for tina flames, scripts, etc.
thanks, Mike

**Comment by thargor6** [comment]
It is recommend to set the paths inside the Preferences, and not edit the config-files manually. 
It is also recommended to change nothing inside the Steam-folderrs, because these files can be overwritten with the next update

**Comment by thargor6** [comment]
There is no screenshot attached. You can see all the paths inside the Preferences. There is no need to look into the Steam-folder
