### ISSUE TITLE
performance: use java.lang.Math.abs(double) instead of org.jwildfire.base.mathlib.MathLib.fabs(double)

### ISSUE THREAD

**Issue by smack42** [thargor6/JWildfire#44]
Why does the home-made function `MathLib.fabs(double)` exist?

The standard function `java.lang.Math.abs(double)` does the same thing and is supposedly faster, because it's an JVM intrinsic function that's replaced by a single CPU instruction (FABS on x86) at runtime.

source: http://stackoverflow.com/a/19892384
http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/classfile/vmSymbols.hpp#l581

**Comment by thargor6** [comment]
Probably some older code, can be replaced by the intrinsic function

Cheers!
